name: meal_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  transparent_image: ^2.0.1
  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.1
  geocoding: 3.0.0
  permission_handler: ^11.3.1
  flutter_share: ^2.0.0
  share_plus: ^10.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
      - assets/images/Bg5.jpg
      - assets/images/Bg4.jpg
      - assets/images/Bg3.jpg
      - assets/images/Bg2.jpg
      - assets/images/Bg1.jpg
      - assets/images/Logo.png
      - assets/images/logofood.svg
      - assets/images/LogoName.png
